configfile: "config/config.yaml"

from pathlib import Path

BASE = Path(config["paths"]["base"])

def p(key):
    return str(BASE / config["paths"][key])

include: "rules/01_data_collection.smk"
include: "rules/02_qc.smk"
include: "rules/03_integration.smk"
include: "rules/04_total_clustering.smk"
include: "rules/05_immune_annotation.smk"

rule all:
    input:
        p("immune_annotation_object")
