METADATA = {'GSM6102532_C01_Ctrl': {'patient_id': 'C01', 'tissue_type': 'healthy', 'condition': 'control', 'lesion_site': None},
 'GSM6102533_C02_Ctrl': {'patient_id': 'C02', 'tissue_type': 'healthy', 'condition': 'control', 'lesion_site': None},
 'GSM6102534_C03_Ctrl': {'patient_id': 'C03', 'tissue_type': 'healthy', 'condition': 'control', 'lesion_site': None},
 'GSM6102537_E01_EuE': {'patient_id': 'E01',
                        'tissue_type': 'eutopic',
                        'condition': 'endometriosis',
                        'lesion_site': None},
 'GSM6102540_E02_EuE': {'patient_id': 'E02',
                        'tissue_type': 'eutopic',
                        'condition': 'endometriosis',
                        'lesion_site': None},
 'GSM6102543_E03_EuE': {'patient_id': 'E03',
                        'tissue_type': 'eutopic',
                        'condition': 'endometriosis',
                        'lesion_site': None},
 'GSM6102546_E04_EuE': {'patient_id': 'E04',
                        'tissue_type': 'eutopic',
                        'condition': 'endometriosis',
                        'lesion_site': None},
 'GSM6102549_E05_EuE': {'patient_id': 'E05',
                        'tissue_type': 'eutopic',
                        'condition': 'endometriosis',
                        'lesion_site': None},
 'GSM6102551_E06_EuE': {'patient_id': 'E06',
                        'tissue_type': 'eutopic',
                        'condition': 'endometriosis',
                        'lesion_site': None},
 'GSM6102554_E07_EuE': {'patient_id': 'E07',
                        'tissue_type': 'eutopic',
                        'condition': 'endometriosis',
                        'lesion_site': None},
 'GSM6102555_E08_EuE': {'patient_id': 'E08',
                        'tissue_type': 'eutopic',
                        'condition': 'endometriosis',
                        'lesion_site': None},
 'GSM6102560_E09_EuE': {'patient_id': 'E09',
                        'tissue_type': 'eutopic',
                        'condition': 'endometriosis',
                        'lesion_site': None},
 'GSM6595248_E01_EcP': {'patient_id': 'E01',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'peritoneal'},
 'GSM6595250_E02_EcP': {'patient_id': 'E02',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'peritoneal'},
 'GSM6595252_E03_EcP': {'patient_id': 'E03',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'peritoneal'},
 'GSM6595254_E04_EcP': {'patient_id': 'E04',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'peritoneal'},
 'GSM6595256_E05_EcP': {'patient_id': 'E05',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'peritoneal'},
 'GSM6102550_E06_EcP': {'patient_id': 'E06',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'peritoneal'},
 'GSM6102553_E07_EcP': {'patient_id': 'E07',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'peritoneal'},
 'GSM6595258_E09_EcP': {'patient_id': 'E09',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'peritoneal'},
 'GSM6102552_E07_EcO': {'patient_id': 'E07',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'ovarian'},
 'GSM6102556_E09_EcO': {'patient_id': 'E09',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'ovarian'},
 'GSM6595261_E10_EcO': {'patient_id': 'E10',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'ovarian'},
 'GSM6102562_E11_EcO': {'patient_id': 'E11',
                        'tissue_type': 'ectopic',
                        'condition': 'endometriosis',
                        'lesion_site': 'ovarian'}}
